fire_servo_range = [65, 150] #90 is onder de buis
fire_delay = 1.0
stepper_range = [0, 300] # tweak this not sure about the range, was not used in old code
communicator = "raw"
shutdown_pin = 17

[raw]
servo_pin = 18 # Servo bundle of three, two red, one black. Ground = black --> green. Signal = red --> purple. Vmot = red --> grey. 
servo_frequency = 50
servo_min_pulse = 1000
servo_max_pulse = 2000
servo_movement_delay = 1
stepper_enable_pin = 16
stepper_direction_pin = 20
stepper_step_pin = 21
stepper_frequency = 250
stepper_delay = 1.0
wheel_left_enable = 12 # Unused 
wheel_left_in1 = 5 # Unused (LET OP beide motoren zitten nu beide op left)
wheel_left_in2 = 13
wheel_right_enable = 26 # Unused
wheel_right_in1 = 6  # Unused
wheel_right_in2 = 19 
limitswitch_pin_right = 24
limitswitch_pin_left = 23

[joystick]
pin_button = 11
pin_left = 10
pin_right = 9
pull_direction = "up"