port = "COM10"
baudrate = 250000
fire_servo_range = [120, 180]
stepper_range = [0,300] # tweak this not sure about the range, was not used in old code
fire_delay = 1.0
fire_servo_name = "P0"
stepper_axis = "X"
stepper_step = 20 # 1 step is 25 (biggen than 25 is 2 steps per time)

#slp pin (pin  via gnd 5 v --> gaat triver uit)