name: build

on: [workflow_dispatch, push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp-contrib/setup-packer@v1
        # id: setup
      # - name: Setup arm packer prerequisites
      #   run: |
      #     sudo add-apt-repository ppa:longsleep/golang-backports
      #     sudo apt-get update
      #     sudo apt-get install golang-go        
      #     sudo apt-get install qemu-user-static
      # - name: Build packer-builder-arm
      #   run: |
      #     git clone https://github.com/mkaczanowski/packer-builder-arm.git
      #     cd packer-builder-arm
      #     go mod download
      #     go build
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.18"
      
    # Install dependencies for packer
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install tree fdisk gdisk qemu-user-static libarchive-tools psmisc tar autoconf make qemu-utils zip

      # Install packer arm plugin
      - name: Install packer-builder-arm
        run: |
          git clone https://github.com/mkaczanowski/packer-builder-arm plugin
          cd plugin
          go mod download
          go build
      - name: init example image
        run: |
          cp plugin/packer-builder-arm .
          sudo packer build packer_test.json

      - name: List dir
        run: |
          pwd
          ls -la
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ubuntu-20.04.img