name: build

on: [workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
      - name: Run `packer init`
        id: init
        run: "packer init ./template.pkr.hcl"
      - name: Run `packer validate`
        id: validate
        run: "packer validate ./template.pkr.hcl"