name: build

on: 
  workflow_dispatch:
    inputs:
      Wifi_SSID:
        description: 'Wifi SSID'
        required: true
        type: string
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Cache packer
        uses: actions/cache@v4
        id: cache-valgrind
        with:
            path: ".packer_cache/"
            key: ${{ runner.os }}-${{ hashFiles('src/install/packer_test.json') }}
      - name: Build
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build -e WIFI_SSID="${{ github.event.inputs.Wifi_SSID }}" mkaczanowski/packer-builder-arm build src/install/packer_test.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: "${{ github.event.inputs.Wifi_SSID }}.img"