name: build

on: [workflow_dispatch, push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build packer_test.json

      - name: List dir
        run: |
          pwd
          ls -la
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ubuntu-20.04.img